config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/new'

  get 'pages/duvidas'

  post 'pages/success'

  get 'pages/cadastro'

  get 'pages/sites'

  get 'pages/sobre'

  resources :categories
  resources :simulators do 
    member do
      put "like", to: "simulators#upvote"
      put "dislike", to: "simulators#downvote"
    end
  end

  root 'simulators#index'
  get 'simulators/:id/like' => 'simulators#like', as: :like_post
  get 'simulators/:id/dislike' => 'simulators#dislike', as: :dislike_post
  get 'static_pages/simulador1'

end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :parent, :class_name => "Category", :foreign_key => "category_id"
	has_many :categories  # TODO adcionar index
	has_many :simulators
	validates :name, presence: true, uniqueness: true
end

app/models/simulator.rb
class Simulator < ActiveRecord::Base
	belongs_to :category
	belongs_to :user
	has_attached_file :icon, styles: { medium: "300x300>", thumb: "200x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :icon, content_type: /\Aimage\/.*\Z/
  	acts_as_votable
  	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_many :simulators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @categories = Category.all.order :category_id
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Categoria criada com êxito.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Categoria atualizada com êxito.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Categoria apagada com êxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :category_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def duvidas
  end

  def sites
  end

  def sobre
  end
end

app/controllers/simulators_controller.rb
class SimulatorsController < ApplicationController
  before_action :set_simulator, only: [:show, :edit, :update, :destroy, :like, :dislike]
  
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  
   before_action :only_mine, only: [:edit, :update, :destroy]

  # GET /simulators
  # GET /simulators.json
  def index
    @simulators = Simulator.all
    @simulators = Simulator.order("name").page(params[:page]).per(6)

    # @simulators = Simulator.order :category_id

    if params[:search].present?
      @simulators = Simulator.where('lower(simulators.name) LIKE ?', "%#{params[:search]}%").order :category_id
      
      categories = Category.where('lower(categories.name) LIKE ?', "%#{params[:search]}%")
      category_simulators = categories.map {|category| category.simulators.to_a}.flatten
      @simulators.push(*category_simulators)
    end

      #@simulators = @simulators.uniq
      # @simulators = Simulator.search(params[:id])
  end

  # GET /simulators/1
  # GET /simulators/1.json
  def show
  end

  # GET /simulators/new
  def new
    @simulator = Simulator.new
  end

  # GET /simulators/1/edit
  def edit
  end

  # POST /simulators
  # POST /simulators.json
  def create
    # @simulator = Simulator.new(simulator_params)
    @simulator = Simulator.create(simulator_params)
    @simulator.user = current_user

    respond_to do |format|
      if @simulator.save
        format.html { redirect_to @simulator, notice: 'Simulador criado com êxito.' }
        format.json { render :show, status: :created, location: @simulator }
      else
        format.html { render :new }
        format.json { render json: @simulator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /simulators/1
  # PATCH/PUT /simulators/1.json
  def update
    respond_to do |format|
      if @simulator.update(simulator_params) 
        format.html { redirect_to @simulator, notice: 'Simulador atualizado com êxito.' }
        format.json { render :show, status: :ok, location: @simulator }
      else
        format.html { render :edit }
        format.json { render json: @simulator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /simulators/1
  # DELETE /simulators/1.json
  def destroy
    @simulator.destroy
    respond_to do |format|
      format.html { redirect_to simulators_url, notice: 'Simulador apagado com êxito.' }
      format.json { head :no_content }
    end
  end

  def upvote 
    @simulator = Simulator.find(params[:id])
    @simulator.upvote_by current_user
    redirect_to :back
  end  

  def downvote
    @simulator = Simulator.find(params[:id])
    @simulator.downvote_by current_user
    redirect_to :back
  end
  
  def like
    @simulator.liked_by current_user

    respond_to do |format|
      if user_signed_in?
        format.html { redirect_to simulators_url, notice: 'Simulador avaliado com êxito!' }
        format.json { head :no_content }
      else
        format.html { redirect_to simulators_url, notice: 'Login necessário.' }
      end
    end
  end
  
  def dislike
    @simulator.disliked_by current_user

    respond_to do |format|
      if user_signed_in?
        format.html { redirect_to simulators_url, notice: 'Simulador avaliado com êxito!' }
        format.json { head :no_content }
      else
        format.html { redirect_to simulators_url, notice: 'Login necessário.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_simulator
      @simulator = Simulator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def simulator_params
      params.require(:simulator).permit(:name, :category_id, :description, :url, :icon)
    end
    
    def only_mine
      if @simulator.user != current_user
        head(403)
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/simulators_helper.rb
module SimulatorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.parent.name if category.parent.present? %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @category.category_id %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>

	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	<meta name="description" content="Free template from FreeWebtemplates.com">
	<meta name="keywords" content="Free template from FreeWebtemplates.com">
	<meta name="revisit-after" content="7days">
	<meta name="robots" content="index, follow">
 
<style type="text/css">
	body,td			{ font-family: arial, helvetica; color: #454545; font-size: 12px; }

	h1{
		color:white;
	}
	

	A:link			{ text-decoration: none; color: #2244ee; }
	A:visited		{ text-decoration: none; color: #2244ee; }
	A:hover			{ text-decoration: underline; color: #000;}

	.hidden			{ font-size: 8px; font-weight: bold; color: #ffffff; }
	A:link.hidden		{ text-decoration: none; color: #ffffff; }
	A:visited.hidden	{ text-decoration: none; color: #ffffff; }
	A:hover.hidden		{ text-decoration: none; color: #ffffff; }

	.small			{ font-size: 10px; }

	.emph			{ font-weight: bold; }
</style>


</head>

<body bgcolor="FFFFFF" TEXT="000000" LINK="0000FF" VLINK="0000FF">


<table border=0 width=80% border=0 cellpading=2 cellspacing=2 align=center bgcolor="#000000">
<tr bgcolor=#0A0089 height=60><td colspan=3>
<center><h1>Simuladores</h1></center>
</td></tr>

<tr bgcolor=#000000><td colspan=3>
<center>
<a href=""><font size=2 face="verdana,arial,helvetica"><b>Link 1</b></font></a> 
&nbsp;
<a href=""><font size=2 face="verdana,arial,helvetica"><b>Link 2</b></font></a> 
&nbsp;
<a href=""><font size=2 face="verdana,arial,helvetica"><b>Link 3</b></font></a> 
&nbsp;
<a href=""><font size=2 face="verdana,arial,helvetica"><b>Link 4</b></font></a> 
&nbsp;
<a href=""><font size=2 face="verdana,arial,helvetica"><b>Link 5</b></font></a> 
&nbsp;
<a href=""><font size=2 face="verdana,arial,helvetica"><b>Link 6</b></font></a> 
&nbsp;
<a href=""><font size=2 face="verdana,arial,helvetica"><b>Link 7</b></font></a> 
</center>
</td></tr>

<tr>

<td Valign=top width="20%" bgcolor=#0A0089 height=800px>

<table border=0 cellpading=0 cellspacing=0 width=100% bgcolor=000000>
<tr><td>&nbsp;<a href=""><font size=2 face="Verdana,arial,helvetica"><b>Link 1</b></font></a></td></tr>
</table><br>

<table border=0 cellpading=0 cellspacing=0 width=100% bgcolor=000000>
<tr><td>&nbsp;<a href=""><font size=2 face="Verdana,arial,helvetica"><b>Link 2</b></font></a></td></tr>
</table><br>

<table border=0 cellpading=0 cellspacing=0 width=100% bgcolor=000000>
<tr><td>&nbsp;<a href=""><font size=2 face="Verdana,arial,helvetica"><b>Link 3</b></font></a></td></tr>
</table><br>

<table border=0 cellpading=0 cellspacing=0 width=100% bgcolor=000000>
<tr><td>&nbsp;<a href=""><font size=2 face="Verdana,arial,helvetica"><b>Link 4</b></font></a></td></tr>
</table><br>

<table border=0 cellpading=0 cellspacing=0 width=100% bgcolor=000000>
<tr><td>&nbsp;<a href=""><font size=2 face="Verdana,arial,helvetica"><b>Link 4</b></font></a></td></tr>
</table><br>

</td>

<td Valign=top width="60%" bgcolor="#ccc">

<table border=0 width=99% align=center>
<tr>

<td Valign=top>

<b>Articles</b><br><br>

<font size=2>

<%= link_to 'Simuladores', simulators_path %>

<br><br>

<%= link_to 'Simulador1', static_pages_simulador1_path %>

<br><br>

<a href="">Article Name 3</a> - brief intro to the article would go here.
Maybe the first two to three lines or the first paragraph. To entice reader to continue.<br>
<font size=1><a href=""><b>Read more here....</b></a></font>

<br><br>

</font>

</td></tr></table>

</td>

<td Valign=top width="20%" bgcolor="#0A0089">

<table border=0 cellpading=0 cellspacing=0 width=100% bgcolor=000000>
<tr><td>&nbsp;<a href=""><font size=2 face="Verdana,arial,helvetica"><b>Sponsor 1</b></font></a></td></tr>
</table>
<table border=0 cellpading=0 cellspacing=0 width=100%>
<tr><td>&nbsp;<font size=1 face="Verdana,arial,helvetica"><b>Texto</b></font></td></tr>
</table><br>

<table border=0 cellpading=0 cellspacing=0 width=100% bgcolor=000000>
<tr><td>&nbsp;<a href=""><font size=2 face="Verdana,arial,helvetica"><b>Sponsor 2</b></font></a></td></tr>
</table>
<table border=0 cellpading=0 cellspacing=0 width=100%>
<tr><td>&nbsp;<font size=1 face="Verdana,arial,helvetica"><b>Texto</b></font></td></tr>
</table><br>

<table border=0 cellpading=0 cellspacing=0 width=100% bgcolor=000000>
<tr><td>&nbsp;<a href=""><font size=2 face="Verdana,arial,helvetica"><b>Sponsor 3</b></font></a></td></tr>
</table>
<table border=0 cellpading=0 cellspacing=0 width=100%>
<tr><td>&nbsp;<font size=1 face="Verdana,arial,helvetica"><b>Texto</b></font></td></tr>
</table><br>


</td>

</tr>


</table>

<center>
<font size=2>
© 2015 <i>Instituto de Tecnologia ORT</i> by Gabriel Fernandes
</font>
</center>

</body>
</html> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= favicon_link_tag 'favicon.ico' %>
  	
    <title>SimulEdu</title>
  	
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>

  	<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
  
<body>
<center>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-header">
           
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" >
            <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
        </button>
        <%= link_to 'SimulEdu', simulators_path, class:"navbar-brand" %>
    </div>
        
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li class="dropdown">
               <a href="" class="dropdown-toggle" data-toggle="dropdown">Categorias<strong class="caret"></strong></a>
              <ul class="dropdown-menu">

              <% category_order = Category.all.order :category_id %>
              <% category_order.each do |category| %>

                <li>
                  <a href="/simulators?search=<%= category.name %>"><%= category.name %></a>
                </li>

              <% end %>
              </ul>
            </li>
            <li class="dropdown">
               <a href="" class="dropdown-toggle" data-toggle="dropdown">Saiba mais<strong class="caret"></strong></a>
              <ul class="dropdown-menu">
                <li>
                  <a href="/pages/duvidas">Dúvidas e Sugestões</a>
                </li>
                <li>
                  <a href="/pages/sites">Sites Interessantes</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="/pages/sobre">Sobre o SimulEdu</a>
            </li>
        </ul>
        <form class="navbar-form navbar-right" name="searchForm" role="search" method="get" action="/simulators" >
            <div class="form-group">
              <input type="text" class="form-control" name="search" placeholder="Pesquisar" autocomplete="off" tabindex="1">
            </div> 
            <button type="submit" class="btn btn-default">
	            Buscar
            </button>
        </form>
    </div>
</nav><br><br><br><br>
<div class="row">
	<div class="col-md-8">
		<p class="breadcrumb" id="cormuda">
      <marquee behavior="scroll" direction="right" scrolldelay="100" style="text-align:center;">
          Descubra, aprenda e divirta-se!
          &#160 &#160 &#160 &#160 &#160 &#160 &#160
          &#160 &#160 &#160 &#160 &#160 &#160 &#160
          <% if user_signed_in? %>
            Olá <%= current_user.email%>
          <% end %>
          &#160 &#160 &#160 &#160 &#160 &#160 &#160
          &#160 &#160 &#160 &#160 &#160 &#160 &#160
          Procure no lugar certo!
      </marquee>
		</p>
	</div>
	<div class="col-md-2">					 
		<p>
		  <%= link_to 'Cadastre-se', new_user_registration_path, class:"btn btn-primary btn-block"  %>  
		</p>
	</div>
	<div class="col-md-2">
	  <p>
			<% if user_signed_in? %>
        <t>
          <%= link_to 'Sair ' +current_user.email, destroy_user_session_path, :method => :delete, class:"btn btn-primary btn-block" %>
        </t>
      <% else %>
        <t>
          <%= link_to 'Entrar', new_user_session_path, class:"btn btn-primary btn-block"  %>
        </t>
      <% end %>
		</p>
	</div>
</div>


<%= yield %>
<hr style="border-color:#303030">
&#169 2015 por Gabriel Fernandes<br>
Instituto de Tecnologia ORT
<br><br>
</center>
</body>
</html>

app/views/pages/cadastro.erb
<h1>Dúvidas e Sugestões</h1>
<p>&nbsp</p><p>&nbsp</p>

<p>Mande sua dúvida ou sugestão:</p>
<br>

<div class="col-md-6 col-md-offset-3">
	<div class="well well-md">
	    <%= form_tag('/simulators', class:"form-horizontal") do %>
	        <fieldset>
	            <legend class="text-center header">Cadastro:</legend>
	            <div class="col-md-10 col-md-offset-1">
	                <div class="form-group">
	                    <div class="col-md-12">
	                        <input id="name" name="name" type="text" placeholder="Nome de Usuário" class="form-control" autocomplete="off" required tabindex="1">
	                    </div>
	                </div>
	            </div>
	            <div class="col-md-10 col-md-offset-1">
	                <div class="form-group">
	                    <div class="col-md-12">
	                        <input id="email" name="email" type="email" placeholder="Email" class="form-control" autocomplete="off" required tabindex="2">
	                    </div>
	                </div>
	            </div>
	            <div class="col-md-10 col-md-offset-1">
	                <div class="form-group">
	                    <div class="col-md-6">
	                        <input id="password" name="password" type="password" placeholder="Digite sua senha" class="form-control" autocomplete="off" required tabindex="3">
	                    </div>
	                    <div class="col-md-6">
	                        <input id="password-confirm" name="password-confirm" type="password" placeholder="Confirme sua senha" class="form-control" autocomplete="off" required tabindex="4">
	                    </div>
	                </div>                            
	            </div>
	            <div class="col-md-10 col-md-offset-1">
	                <div class="form-group">
	                    <div class="col-md-6">
	                        <input id="idade" name="idade" type="number" placeholder="Idade" class="form-control" autocomplete="off" required tabindex="5">
	                    </div>
	                    <div class="checkbox">
		                    <label style="color:#505050">
		                        <input type="checkbox" id="checkbox" name="checkbox" tabindex="6">Emails sobre novos simuladores
		                    </label>
	                    </div>
	                </div>
	            </div>
	            
	            <div class="form-group">
	                <div class="col-md-12 text-center">
	                	<input type="submit" class="btn btn-primary" tabindex:"7">
	                </div>
	            </div>
	        </fieldset>
	    <% end %>
	</div>
</div>
<br>
<p>&nbsp</p>
<p>&nbsp</p><p>&nbsp</p><p>&nbsp</p>
<p>&nbsp</p><p>&nbsp</p><p>&nbsp</p>
<p>&nbsp</p><p>&nbsp</p><p>&nbsp</p>
<br>

<div class="col-md-12">
    <%= link_to 'Voltar', simulators_path, class:"btn btn-primary", tabindex:"8" %>
</div><br><br><br><br>

app/views/pages/duvidas.html.erb
<h1>Dúvidas e Sugestões</h1>
<p>&nbsp</p><p>&nbsp</p>

<p>Mande sua dúvida ou sugestão:</p>
<br>

<div class="col-md-6 col-md-offset-3">
	<div class="well well-md">
	    <%= form_tag('/pages/success', class:"form-horizontal") do %>
	        <fieldset>
	            <legend class="text-center header">Fale Conosco:</legend>
	            <div class="col-md-6" height="400px">
	                <div class="form-group">
	                    <div class="col-md-11 col-md-offset-1">
	                        <input id="name" name="name" type="text" placeholder="Nome" class="form-control" autocomplete="off" required tabindex="1">
	                    </div>
	                </div>

	                <div class="form-group">
	                    <div class="col-md-11 col-md-offset-1">
	                        <input id="email" name="email" type="email" placeholder="Email" class="form-control" autocomplete="off" required tabindex="2">
	                    </div>
	                </div>

	                <div class="form-group">
	                    <div class="col-md-11 col-md-offset-1">
	                        <input id="assunto" name="assunto" type="text" placeholder="Assunto" class="form-control" autocomplete="off" required tabindex="3">
	                    </div>
	                </div>
	            </div>
	            <div class="col-md-6">
	                <div class="form-group">
	                    <div class="col-md-11">
	                        <textarea class="form-control" id="message" name="message" placeholder="Escreva aqui" rows="6" required tabindex="4"></textarea>
	                    </div>
	                </div>
                            
	            </div>

	            <div class="form-group">
	                <div class="col-md-12 text-center">
	                	<input type="submit" class="btn btn-primary" tabindex:"5">
	                </div>
	            </div>
	        </fieldset>
	    <% end %>
	</div>
</div>
<br>
<p>&nbsp</p>
<p>&nbsp</p><p>&nbsp</p><p>&nbsp</p>
<p>&nbsp</p><p>&nbsp</p><p>&nbsp</p>
<p>&nbsp</p><p>&nbsp</p><p>&nbsp</p>
<br>

<div>
    <%= link_to 'Voltar', simulators_path, class:"btn btn-primary", tabindex:"6" %>
</div>

app/views/simulators/edit.html.erb
<h1>Editar Simulador</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @simulator %> |
<%= link_to 'Voltar', simulators_path %>

app/views/simulators/index.html.erb
<p id="notice"><%= notice %></p>

<div class="btn btn-block">
  <hr style="border:5px outset #404040;">

  <h1 style="font-size:400%; font-weight: bold; font-family: serif; border:5px groove #404040" id="mudacor">
    <t id="color_red">S</t>IMUL<t id="color_blue">E</t>DU
  </h1>

  <hr style="border:5px outset #404040">
</div>

<br>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
<% @simulators.each do |simulator| %>
        <div class="col-md-6" style="height:400px; /*border:5px solid black*/">
          <div class="col-md-12">
            <div class="col-md-6">
              <p style="font-weight:normal">
                Cadastrado em <%= (simulator.created_at.strftime("%B %d %Y")) %>
              </p>
              <a target="_blank" class="thumnail" href="<%= simulator.url %>">
                <%= image_tag simulator.icon.url, class:"img-thumbnail", width:"300" %>
              </a><br><br>
              
              <t aria-hidden="true">
                <%= link_to 'Like', like_simulator_path(simulator), class:"btn btn-success" %>
              </t>
              <t aria-hidden="true">
                <%= link_to 'Dislike', dislike_simulator_path(simulator), class:"btn btn-danger" %>
              </t>
              
              <br><br>
              Likes <span class="badge" ><%= (simulator.get_upvotes.size) %></span>
              Dislikes <span class="badge" ><%= (simulator.get_downvotes.size) %></span>
              <br><br>
            </div>
            <div class="col-md-6">
              <h3>
                <%= simulator.name %>
              </h3>
               <p>
                <span class="label label-info" style="color:#000;">
                  <%=  simulator.category.name %>
                </span>
              </p>
              <p class="alert panel-primary" style="text-align:left;">
                <%= simulator.description %>
              </p>
              <div class="btn-group btn-primary" role="group" aria-label="bgroup">
                <a><%= link_to 'Exibir', simulator, class:"btn btn-primary" %></a>
                <a><%= link_to 'Editar', edit_simulator_path(simulator), class:"btn btn-primary" %></a>
                <a><%= link_to 'Apagar', simulator, method: :delete, data: { confirm: 'Deseja continuar?' }, class:"btn btn-primary" %></a>
              </div><br><br>
              <p>
                <%= link_to 'Ver Agora', simulator.url, target:"_blank", :class => "btn btn-lg btn-primary" %>
              </p>
            </div>
          </div>
        </div>
<% end %>   
      </div>
    </div>    
  </div>
<br>

<div class="btn-group" role="group" aria-label="label">
  <a class="btn btn-primary" href="/simulators">1</a>
  <a class="btn btn-primary" href="/simulators?page=2">2</a>
  <a class="btn btn-primary" href="/simulators?page=3">3</a>
  <!--<a class="btn btn-primary" href="/simulators?page=4">4</a>
  <a class="btn btn-primary" href="/simulators?page=5">5</a>
  <a class="btn btn-primary" href="/simulators?page=6">6</a>-->
</div><br><br>

<p>
  <%= link_to 'Novo Simulador', new_simulator_path, class:"btn btn-primary" %>
</p>

app/views/simulators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @simulator.name %>
</p>

<p>
  <strong>Categoria:</strong>
  <%##= @simulator.category.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @simulator.url %>
</p>

<%= link_to 'Editar', edit_simulator_path(@simulator) %> |
<%= link_to 'Voltar', simulators_path %>